services:
  alsa-deploy:
    build:
      context: ./build
      dockerfile: Dockerfile
      target: deploy
    user: user
    working_dir: /home/user
    hostname: alsa-docker
    environment:
      - XDG_RUNTIME_DIR=/tmp
    volumes:
      - type: bind
        source: /run/user/1000/pipewire-0
        target: /tmp/pipewire-0
      - type: bind
        source: ../examples
        target: /home/user/examples
      - type: bind
        source: ../src
        target: /home/user/src
      - type: bind
        source: ../audio
        target: /home/user/audio
      - type: bind
        source: ./scripts
        target: /scripts
    entrypoint: /scripts/deploy_entrypoint.sh

  alsa-devel:
    build:
      target: devel
    extends: alsa-deploy
    entrypoint: /scripts/devel_entrypoint.sh
